### ISSUE TITLE
Poor performance when using [!Mormon] tag

### ISSUE THREAD

**Issue by ethancedwards8** [pacokwon/obsidian-lds-scriptures-plugin#2]
Hello,

# Problem
Some of my LDS friends have found this plugin and tried to use it but they found it to hurt their obsidian performance quite a bit. They asked me to try it and see if I could figure out why. Testing on Arch Linux (x86_64)

# Testing
I tried out `+Genesis 1:1-20` and everything formatted as expected:
```
> [!Mormon] [Genesis 1:1-20](https://www.churchofjesuschrist.org/study/scriptures/ot/gen/1?lang=eng&id=p1-p20#p1)
> <ol start="1"><li>In the beginning God created the heaven and the earth.</li> <li>And the earth was without form, and void; and darkness was upon the face of the deep. And the Spirit of God moved upon the face of the waters.</li> <li>And God said, Let there be light: and there was light.</li> <li>And God saw the light, that it was good: and God divided the light from the darkness.</li> <li>And God called the light Day, and the darkness he called Night. And the evening and the morning were the first day.</li> <li>¶ And God said, Let there be a firmament in the midst of the waters, and let it divide the waters from the waters.</li> <li>And God made the firmament, and divided the waters which were under the firmament from the waters which were above the firmament: and it was so.</li> <li>And God called the firmament Heaven. And the evening and the morning were the second day.</li> <li>¶ And God said, Let the waters under the heaven be gathered together unto one place, and let the dry land appear: and it was so.</li> <li>And God called the dry land Earth; and the gathering together of the waters called he Seas: and God saw that it was good.</li> <li>And God said, Let the earth bring forth grass, the herb yielding seed, and the fruit tree yielding fruit after his kind, whose seed is in itself, upon the earth: and it was so.</li> <li>And the earth brought forth grass, and herb yielding seed after his kind, and the tree yielding fruit, whose seed was in itself, after his kind: and God saw that it was good.</li> <li>And the evening and the morning were the third day.</li> <li>¶ And God said, Let there be lights in the firmament of the heaven to divide the day from the night; and let them be for signs, and for seasons, and for days, and years:</li> <li>And let them be for lights in the firmament of the heaven to give light upon the earth: and it was so.</li> <li>And God made two great lights; the greater light to rule the day, and the lesser light to rule the night: he made the stars also.</li> <li>And God set them in the firmament of the heaven to give light upon the earth,</li> <li>And to rule over the day and over the night, and to divide the light from the darkness: and God saw that it was good.</li> <li>And the evening and the morning were the fourth day.</li> <li>And God said, Let the waters bring forth abundantly the moving creature that hath life, and fowl that may fly above the earth in the open firmament of heaven.</li></ol>
```

but when going into reading mode my performance would drop significantly when scrolling. 

# Solution
I tried a few different things and eventually discovered that if you removed the `[!Mormon]` from the inserted text then performance significantly improved. This also impacted styling when rendered. This makes me think there exists some type of inefficiency. I'll look through the code and see if I can find any solution that retains the styling but improves performance.

**Comment by ethancedwards8** [comment]
Found this file: https://github.com/pacokwon/obsidian-lds-scriptures-plugin/blob/main/styles.css , it seems that this is using the [callouts](https://help.obsidian.md/Editing+and+formatting/Callouts) feature. It seems this feature, regardless of how I use it, creates performance issues and I suspect that it does the same for my friends. Maybe the plugin could use something else? Not sure if it is just a weird niche issue or if it is more widespread.

**Comment by pacokwon** [comment]
Thank you for the report. I'm glad it's getting some use.

Hmm that's strange because I'm on Arch Linux x86 as well and it doesn't seem to cause any issues for me. How is the performance issue manifested? ex> does it stutter when you scroll in read only mode?

You also mentioned the callouts feature itself being an issue. Does just using callouts and not this plugin's feature also affect performance?

**Comment by ethancedwards8** [comment]
> Thank you for the report. I'm glad it's getting some use.
> 
> Hmm that's strange because I'm on Arch Linux x86 as well and it doesn't seem to cause any issues for me. How is the performance issue manifested? ex> does it stutter when you scroll in read only mode?
Yes
> 
> You also mentioned the callouts feature itself being an issue. Does just using callouts and not this plugin's feature also affect performance?
Yes

It's worth noting that I use the built in Nvidia drivers on my PC and that I do not have this performance issue on my macbook. So this could totally just be a rendering issue and nothing wrong with the obsidian software or plugin implementation.

**Comment by pacokwon** [comment]
If the callouts feature itself is a problem, then there's not much that I, as the plugin developer, can do about it.

It might be a workaround to implement the feature without using the callouts feature, but I'm actually leaving on my mission in a few days and won't be able to develop that feature myself.

So as of now, that is how it is!

**Comment by ethancedwards8** [comment]
> If the callouts feature itself is a problem, then there's not much that I, as the plugin developer, can do about it. It might help to file an issue to the obsidian repository.
> 

Yeah. I figured.
> It might be a workaround to implement the feature without using the callouts feature, but I'm actually leaving on my mission in a few days and won't be able to develop that feature myself.

I was thinking about that but not much to do, you're right. Thanks anyway. Good luck.
